package com.company.oop.taskManagementSystem.commands.enums;

public enum CommandType {
    LOGIN,
    LOGOUT,
    CREATEMEMBER,
    SHOWMEMBERACTIVITY,
    SHOWMEMBERS,
    SHOWTEAMS,
    SHOWTEAMACTIVITY,
    SHOWTEAMMEMBERS,
    ADDMEMBERTOTEAM,
    CREATEBOARDINTEAM,
    SHOWTEAMBOARDS,
    CREATEFEEDBACK,
    SHOWBOARDACTIVITY,
    CREATESTORY,
    CREATETEAM,
    CREATEBUG,
    ADDCOMMENTTOTASK;
}
